/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthStatusDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetupRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CurrentUserDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CurrentUserDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChangePasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/language": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetLanguageRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ForgotPasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ResetPasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CurrentUserDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/mail/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TestMailResult"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Bad Gateway */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/mail/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MailSettingsDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SaveMailSettingsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MailSettingsDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MailSettingsDto"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/server/language": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServerLanguageDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SaveServerLanguageRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServerLanguageDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/storage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StorageReportResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    applicationId?: string;
                    namespace?: string;
                    environment?: string;
                    service?: string;
                    severityMin?: number | string;
                    range?: string;
                    from?: string;
                    to?: string;
                    q?: string;
                    traceId?: string;
                    attr?: string[];
                    res?: string[];
                    before?: string;
                    beforeId?: number | string;
                    after?: string;
                    afterId?: number | string;
                    limit?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SearchLogsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    applicationId?: string;
                    namespace?: string;
                    environment?: string;
                    service?: string;
                    severityMin?: number | string;
                    range?: string;
                    from?: string;
                    to?: string;
                    q?: string;
                    traceId?: string;
                    attr?: string[];
                    res?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LogCountResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/volume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    applicationId?: string;
                    namespace?: string;
                    environment?: string;
                    service?: string;
                    severityMin?: number | string;
                    range?: string;
                    from?: string;
                    to?: string;
                    q?: string;
                    traceId?: string;
                    attr?: string[];
                    res?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LogVolumeResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/volume/by-service": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    applicationId?: string;
                    namespace?: string;
                    environment?: string;
                    service?: string;
                    severityMin?: number | string;
                    range?: string;
                    from?: string;
                    to?: string;
                    q?: string;
                    traceId?: string;
                    attr?: string[];
                    res?: string[];
                    buckets?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LogVolumeByServiceResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    applicationId?: string;
                    namespace?: string;
                    environment?: string;
                    service?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ObservedKeysResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LogRecordDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    applicationId?: string;
                    namespace?: string;
                    environment?: string;
                    service?: string;
                    range?: string;
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReleasesResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    applicationId?: string;
                    namespace?: string;
                    environment?: string;
                    service?: string;
                    range?: string;
                    from?: string;
                    to?: string;
                    errorsOnly?: boolean;
                    attr?: string[];
                    res?: string[];
                    limit?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListTracesResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/traces/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    applicationId?: string;
                    namespace?: string;
                    environment?: string;
                    service?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ObservedKeysResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/traces/{traceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    traceId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TraceDetailResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CatalogResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateUserRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/reset-ticket": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IssuedResetTicketDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GrantRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/grants/{applicationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    applicationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/applications/{applicationId}/alerting": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    applicationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApplicationAlertingDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    applicationId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetApplicationAlertingRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/applications/{applicationId}/alerting/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    applicationId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetChatWebhookRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/services/{serviceId}/alerting": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    serviceId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetServiceAlertingRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SetServiceAlertingResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/episodes/{id}/quiet-window": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetFingerprintQuietWindowRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerting/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubscriptionsDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetSubscriptionsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerting/episodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    applicationId?: string;
                    serviceId?: string[];
                    state?: components["schemas"]["EpisodeState"][];
                    fingerprint?: string;
                    from?: string;
                    q?: string;
                    acknowledged?: string;
                    latestPerFingerprint?: boolean;
                    beforeId?: string;
                    limit?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListEpisodesResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerting/episodes/counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    applicationId?: string;
                    serviceId?: string[];
                    fingerprint?: string;
                    from?: string;
                    q?: string;
                    acknowledged?: string;
                    latestPerFingerprint?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EpisodeCountsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerting/episodes/by-service": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    applicationId?: string;
                    serviceId?: string[];
                    fingerprint?: string;
                    from?: string;
                    q?: string;
                    acknowledged?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EpisodesByServiceResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerting/episodes/{id}/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EpisodeDetailDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerting/sensitivity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListSensitivityResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerting/episodes/{id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerting/episodes/{id}/acknowledgement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerting/episodes/{id}/solve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApplicationDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateApplicationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApplicationDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/applications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/applications/{applicationId}/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    applicationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceListDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateServiceRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/services/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/services/{id}/retention": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetRetentionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/services/{id}/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiKeyDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IssuedApiKeyDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AlertingDefaultsDto: {
            sensitivity: components["schemas"]["Sensitivity"];
            /** Format: int32 */
            quietWindowMinutes: number | string;
        };
        ApiKeyDto: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            revokedAt: null | string;
        };
        ApplicationAlertingDto: {
            /** Format: uuid */
            applicationId: string;
            sensitivity: null | components["schemas"]["Sensitivity"];
            /** Format: int32 */
            quietWindowMinutes: null | number | string;
            chatWebhook: null | components["schemas"]["ChatWebhookDto"];
            serviceOverrides: components["schemas"]["ServiceAlertingOverrideDto"][];
            defaults: components["schemas"]["AlertingDefaultsDto"];
        };
        ApplicationDto: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: date-time */
            createdAt: string;
        };
        AuthStatusDto: {
            needsSetup: boolean;
            passwordResetAvailable: boolean;
            language: string;
        };
        CatalogApplicationDto: {
            /** Format: uuid */
            id: string;
            name: string;
            services: components["schemas"]["CatalogServiceDto"][];
        };
        CatalogResponse: {
            applications: components["schemas"]["CatalogApplicationDto"][];
        };
        CatalogServiceDto: {
            /** Format: uuid */
            id: string;
            namespace: string;
            environment: string;
            name: string;
        };
        CreateApplicationRequest: {
            name: string;
        };
        CreateServiceRequest: {
            /** Format: uuid */
            applicationId: string;
            namespace: string;
            environment: string;
            name: string;
            /** Format: int32 */
            retentionDays: null | number | string;
            /** Format: int32 */
            traceRetentionDays: null | number | string;
        };
        CreateUserRequest: {
            email: string;
            password: string;
            displayName: null | string;
            isAdmin: boolean;
        };
        CurrentUserDto: {
            /** Format: uuid */
            id: string;
            email: string;
            displayName: null | string;
            isAdmin: boolean;
            grantedApplicationIds: string[];
            language: null | string;
        };
        EpisodeCountsResponse: {
            /** Format: int32 */
            open: number | string;
            /** Format: int32 */
            quieted: number | string;
            /** Format: int32 */
            solved: number | string;
            /** Format: int32 */
            muted: number | string;
        };
        EpisodeDetailDto: {
            episode: components["schemas"]["EpisodeDto"];
            mailAlert: null | components["schemas"]["MailAlertDto"];
            chatAlert: null | components["schemas"]["ChatAlertDto"];
            effectiveSensitivity: components["schemas"]["Sensitivity"];
            /** Format: int32 */
            quietWindowMinutes: number | string;
            /** Format: int32 */
            inheritedQuietWindowMinutes: number | string;
            journal: components["schemas"]["JournalEntryDto"][];
        };
        EpisodeDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            applicationId: string;
            /** Format: uuid */
            serviceId: string;
            watch: components["schemas"]["Watch"];
            fingerprint: string;
            state: components["schemas"]["EpisodeState"];
            /** Format: date-time */
            openedAt: string;
            /** Format: date-time */
            closedAt: null | string;
            /** Format: date-time */
            lastMatchAt: string;
            /** Format: int32 */
            errorCount: number | string;
            /** Format: int32 */
            warnCount: number | string;
            /** Format: int64 */
            firstMatchLogId: null | number | string;
            /** Format: date-time */
            firstMatchAt: string;
            /** Format: int16 */
            firstMatchSeverity: null | number | string;
            firstMatchDetail: null | string;
            /** Format: date-time */
            acknowledgedAt: null | string;
            acknowledgedBy: null | string;
            /** Format: date-time */
            solvedAt: null | string;
            solvedBy: null | string;
            /** Format: date-time */
            earlierAcknowledgedAt: null | string;
            earlierAcknowledgedBy: null | string;
            /** Format: int32 */
            priorCount: number | string;
            /** Format: int32 */
            fingerprintQuietWindowMinutes: null | number | string;
        };
        EpisodesByServiceResponse: {
            services: components["schemas"]["ServiceEpisodesDto"][];
        };
        /** @enum {unknown} */
        EpisodeState: "Open" | "Quieted" | "Solved" | "Muted";
        EpisodeSummaryDto: {
            /** Format: uuid */
            id: string;
            state: components["schemas"]["EpisodeState"];
            /** Format: date-time */
            openedAt: string;
            /** Format: date-time */
            closedAt: null | string;
            /** Format: date-time */
            lastMatchAt: string;
            /** Format: int32 */
            errorCount: number | string;
            /** Format: int32 */
            warnCount: number | string;
            watch: components["schemas"]["Watch"];
            /** Format: int16 */
            firstMatchSeverity: null | number | string;
            firstMatchDetail: null | string;
        };
        ForgotPasswordRequest: {
            email: string;
        };
        GrantRequest: {
            /** Format: uuid */
            applicationId: string;
        };
        HealthCheckProbeDto: {
            alive: boolean;
            detail: string;
        };
        ChangePasswordRequest: {
            currentPassword: string;
            newPassword: string;
        };
        ChatAlertDto: {
            /** Format: date-time */
            deliveredAt: null | string;
        };
        ChatWebhookDto: {
            domain: string;
        };
        IssuedApiKeyDto: {
            /** Format: uuid */
            id: string;
            plaintext: string;
        };
        IssuedResetTicketDto: {
            link: string;
            /** Format: date-time */
            expiresAt: string;
        };
        JournalEntryDto: {
            kind: components["schemas"]["JournalEntryKind"];
            /** Format: date-time */
            at: string;
            by: null | string;
        };
        /** @enum {unknown} */
        JournalEntryKind: "Acknowledged" | "Withdrawn" | "Solved";
        JsonElement: unknown;
        ListEpisodesResponse: {
            items: components["schemas"]["EpisodeDto"][];
        };
        ListSensitivityResponse: {
            items: components["schemas"]["ServiceSensitivityDto"][];
        };
        ListTracesResponse: {
            items: components["schemas"]["TraceSummaryDto"][];
        };
        LogCountResponse: {
            /** Format: int32 */
            total: number | string;
            capped: boolean;
        };
        LoginRequest: {
            email: string;
            password: string;
            /** @default false */
            staySignedIn: boolean;
        };
        LogRecordDto: {
            /** Format: int64 */
            id: number | string;
            /** Format: uuid */
            serviceId: string;
            /** Format: date-time */
            timestamp: string;
            /** Format: date-time */
            observedTimestamp: null | string;
            /** Format: int16 */
            severityNumber: number | string;
            severityText: null | string;
            body: null | string;
            traceId: null | string;
            spanId: null | string;
            scopeName: null | string;
            resourceAttributes: components["schemas"]["JsonElement"];
            attributes: components["schemas"]["JsonElement"];
        };
        LogVolumeByServiceResponse: {
            /** Format: date-time */
            from: string;
            /** Format: date-time */
            to: string;
            bucket: string;
            services: components["schemas"]["ServiceVolumeDto"][];
        };
        LogVolumeResponse: {
            /** Format: date-time */
            from: string;
            /** Format: date-time */
            to: string;
            /** Format: date-time */
            now: string;
            bucket: string;
            buckets: components["schemas"]["VolumeBucketDto"][];
        };
        MailAlertDto: {
            /** Format: int32 */
            subscriberCount: number | string;
            /** Format: date-time */
            firstDeliveredAt: null | string;
        };
        MailSettingsDto: {
            source: components["schemas"]["MailSettingsSource"];
            host: string;
            /** Format: int32 */
            port: number | string;
            security: components["schemas"]["SmtpSecurity"];
            username: string;
            hasPassword: boolean;
            from: string;
        };
        /** @enum {unknown} */
        MailSettingsSource: "Configuration" | "Stored";
        ObservedKeyDto: {
            scope: string;
            path: string[];
        };
        ObservedKeysResponse: {
            items: components["schemas"]["ObservedKeyDto"][];
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        ReleaseDto: {
            /** Format: uuid */
            serviceId: string;
            version: string;
            previousVersion: string;
            /** Format: date-time */
            at: string;
        };
        ReleasesResponse: {
            /** Format: date-time */
            from: null | string;
            /** Format: date-time */
            to: null | string;
            /** Format: date-time */
            now: string;
            running: components["schemas"]["RunningVersionDto"][];
            releases: components["schemas"]["ReleaseDto"][];
        };
        ResetPasswordRequest: {
            token: string;
            newPassword: string;
        };
        RunningVersionDto: {
            /** Format: uuid */
            serviceId: string;
            version: string;
            /** Format: date-time */
            since: string;
        };
        SaveMailSettingsRequest: {
            host: string;
            /** Format: int32 */
            port: number | string;
            security: components["schemas"]["SmtpSecurity"];
            username: null | string;
            password: null | string;
            from: string;
        };
        SaveServerLanguageRequest: {
            language: string;
        };
        SearchLogsResponse: {
            items: components["schemas"]["LogRecordDto"][];
        };
        /** @enum {unknown} */
        Sensitivity: "Off" | "Errors" | "ErrorsAndWarnings" | null;
        ServerLanguageDto: {
            language: string;
        };
        ServiceAlertingOverrideDto: {
            /** Format: uuid */
            serviceId: string;
            sensitivity: null | components["schemas"]["Sensitivity"];
            /** Format: int32 */
            quietWindowMinutes: null | number | string;
            healthCheckUrl: null | string;
        };
        ServiceDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            applicationId: string;
            namespace: string;
            environment: string;
            name: string;
            /** Format: int32 */
            retentionDays: null | number | string;
            /** Format: int32 */
            traceRetentionDays: null | number | string;
            /** Format: date-time */
            createdAt: string;
        };
        ServiceEpisodesDto: {
            /** Format: uuid */
            serviceId: string;
            /** Format: int32 */
            open: number | string;
            /** Format: int32 */
            quieted: number | string;
            /** Format: int32 */
            solved: number | string;
            /** Format: int32 */
            muted: number | string;
            latest: null | components["schemas"]["EpisodeSummaryDto"];
        };
        ServiceListDto: {
            /** Format: int32 */
            defaultRetentionDays: number | string;
            /** Format: int32 */
            defaultTraceRetentionDays: number | string;
            services: components["schemas"]["ServiceDto"][];
        };
        ServiceSensitivityDto: {
            /** Format: uuid */
            serviceId: string;
            off: boolean;
        };
        ServiceStorageDto: {
            /** Format: uuid */
            serviceId: string;
            logs: components["schemas"]["SignalStorageDto"];
            traces: components["schemas"]["SignalStorageDto"];
        };
        ServiceVolumeDto: {
            /** Format: uuid */
            serviceId: string;
            /** Format: int32 */
            error: number | string;
            /** Format: int32 */
            warn: number | string;
            /** Format: int32 */
            info: number | string;
            /** Format: int32 */
            debug: number | string;
            buckets: components["schemas"]["VolumeBucketDto"][];
        };
        SetApplicationAlertingRequest: {
            sensitivity: null | components["schemas"]["Sensitivity"];
            /** Format: int32 */
            quietWindowMinutes: null | number | string;
        };
        SetFingerprintQuietWindowRequest: {
            /** Format: int32 */
            quietWindowMinutes: null | number | string;
        };
        SetChatWebhookRequest: {
            url: null | string;
        };
        SetLanguageRequest: {
            language: null | string;
        };
        SetRetentionRequest: {
            /** Format: int32 */
            retentionDays: null | number | string;
            /** Format: int32 */
            traceRetentionDays: null | number | string;
        };
        SetServiceAlertingRequest: {
            sensitivity: null | components["schemas"]["Sensitivity"];
            /** Format: int32 */
            quietWindowMinutes: null | number | string;
            healthCheckUrl: null | string;
        };
        SetServiceAlertingResponse: {
            healthCheck: null | components["schemas"]["HealthCheckProbeDto"];
        };
        SetSubscriptionsRequest: {
            applicationIds: string[];
            serviceIds: string[];
        };
        SetupRequest: {
            email: string;
            password: string;
            displayName: null | string;
        };
        SignalStorageDto: {
            /** Format: int64 */
            footprintBytes: number | string;
            /** Format: int32 */
            retentionDays: number | string;
            /** Format: int64 */
            windowBytes: number | string;
        };
        /** @enum {unknown} */
        SmtpSecurity: "Automatic" | "None" | "StartTls" | "ImplicitTls";
        StorageReportResponse: {
            /** Format: date-time */
            windowStart: string;
            /** Format: date-time */
            windowEnd: string;
            /** Format: int64 */
            logTableBytes: number | string;
            /** Format: int64 */
            traceTableBytes: number | string;
            services: components["schemas"]["ServiceStorageDto"][];
        };
        SubscriptionsDto: {
            applicationIds: string[];
            serviceIds: string[];
        };
        TestMailResult: {
            sentTo: string;
        };
        TraceDetailResponse: {
            traceId: string;
            spans: components["schemas"]["TraceSpanDto"][];
        };
        TraceSpanDto: {
            /** Format: int64 */
            id: number | string;
            /** Format: uuid */
            serviceId: string;
            spanId: string;
            parentSpanId: null | string;
            name: string;
            /** Format: int16 */
            kind: number | string;
            /** Format: date-time */
            startTime: string;
            /** Format: date-time */
            endTime: string;
            /** Format: int16 */
            statusCode: number | string;
            statusMessage: null | string;
            scopeName: null | string;
            resourceAttributes: components["schemas"]["JsonElement"];
            attributes: components["schemas"]["JsonElement"];
            events: components["schemas"]["JsonElement"];
            links: components["schemas"]["JsonElement"];
        };
        TraceSummaryDto: {
            traceId: string;
            /** Format: date-time */
            startTime: string;
            /** Format: double */
            durationMs: number | string;
            /** Format: int32 */
            spanCount: number | string;
            hasError: boolean;
            rootName: null | string;
            /** Format: uuid */
            rootServiceId: null | string;
        };
        UserDto: {
            /** Format: uuid */
            id: string;
            email: string;
            displayName: null | string;
            isAdmin: boolean;
            isDeactivated: boolean;
            grantedApplicationIds: string[];
        };
        VolumeBucketDto: {
            /** Format: date-time */
            start: string;
            /** Format: int32 */
            error: number | string;
            /** Format: int32 */
            warn: number | string;
            /** Format: int32 */
            info: number | string;
            /** Format: int32 */
            debug: number | string;
        };
        /** @enum {unknown} */
        Watch: "Logs" | "HealthCheck";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
