// <auto-generated />
using System;
using Bugler.Ingestion.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bugler.Ingestion.Storage.Migrations
{
    [DbContext(typeof(IngestionDbContext))]
    [Migration("20260728132956_RenameInstanceToService")]
    partial class RenameInstanceToService
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("telemetry")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bugler.Ingestion.Storage.IngestionDbContext+StoredLogRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes");

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime?>("ObservedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_timestamp");

                    b.Property<string>("ResourceAttributes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("resource_attributes");

                    b.Property<string>("ScopeName")
                        .HasColumnType("text")
                        .HasColumnName("scope_name");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<short>("SeverityNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("severity_number");

                    b.Property<string>("SeverityText")
                        .HasColumnType("text")
                        .HasColumnName("severity_text");

                    b.Property<string>("SpanId")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("span_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("TraceId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("trace_id");

                    b.HasKey("Id")
                        .HasName("pk_log_records");

                    b.HasIndex("Attributes")
                        .HasDatabaseName("ix_log_records_attributes");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Attributes"), "gin");

                    b.HasIndex("TraceId")
                        .HasDatabaseName("ix_log_records_trace_id");

                    b.HasIndex("ServiceId", "Timestamp")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_log_records_service_id_timestamp");

                    b.ToTable("log_records", "telemetry");
                });

            modelBuilder.Entity("Bugler.Ingestion.Storage.IngestionDbContext+StoredSpan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("Events")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("events");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<string>("Links")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("links");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ParentSpanId")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("parent_span_id");

                    b.Property<string>("ResourceAttributes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("resource_attributes");

                    b.Property<string>("ScopeName")
                        .HasColumnType("text")
                        .HasColumnName("scope_name");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<string>("SpanId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("span_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<short>("StatusCode")
                        .HasColumnType("smallint")
                        .HasColumnName("status_code");

                    b.Property<string>("StatusMessage")
                        .HasColumnType("text")
                        .HasColumnName("status_message");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("trace_id");

                    b.HasKey("Id")
                        .HasName("pk_spans");

                    b.HasIndex("Attributes")
                        .HasDatabaseName("ix_spans_attributes");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Attributes"), "gin");

                    b.HasIndex("TraceId")
                        .HasDatabaseName("ix_spans_trace_id");

                    b.HasIndex("ServiceId", "StartTime")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_spans_service_id_start_time");

                    b.ToTable("spans", "telemetry");
                });
#pragma warning restore 612, 618
        }
    }
}
