// <auto-generated />
using System;
using Bugler.Ingestion.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bugler.Ingestion.Storage.Migrations
{
    [DbContext(typeof(IngestionDbContext))]
    partial class IngestionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("telemetry")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bugler.Ingestion.Storage.IngestionDbContext+StoredLogRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes");

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<DateTime?>("ObservedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_timestamp");

                    b.Property<string>("ResourceAttributes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("resource_attributes");

                    b.Property<string>("ScopeName")
                        .HasColumnType("text")
                        .HasColumnName("scope_name");

                    b.Property<string>("ServiceName")
                        .HasColumnType("text")
                        .HasColumnName("service_name");

                    b.Property<short>("SeverityNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("severity_number");

                    b.Property<string>("SeverityText")
                        .HasColumnType("text")
                        .HasColumnName("severity_text");

                    b.Property<string>("SpanId")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("span_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("TraceId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("trace_id");

                    b.HasKey("Id")
                        .HasName("pk_log_records");

                    b.HasIndex("Attributes")
                        .HasDatabaseName("ix_log_records_attributes");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Attributes"), "gin");

                    b.HasIndex("TraceId")
                        .HasDatabaseName("ix_log_records_trace_id");

                    b.HasIndex("InstanceId", "Timestamp")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_log_records_instance_id_timestamp");

                    b.ToTable("log_records", "telemetry");
                });
#pragma warning restore 612, 618
        }
    }
}
