// Compiles the design-sync stylesheet: the app's real Tailwind v4 CSS with
// extra source scans (frontend/src + .design-sync/previews) so component
// classes, preview compositions, and app-used glue utilities all generate.
// Output: frontend/.ds-css/entry.css (gitignored; consumed as cfg.cssEntry)
// plus tokens.css (consumed via cfg.tokensPkg/tokensGlob).
import tailwind from "bun-plugin-tailwind";
import { readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";

const frontendDir = path.dirname(import.meta.dir);
const outdir = path.join(frontendDir, ".ds-css");
await rm(outdir, { recursive: true, force: true });

const result = await Bun.build({
  entrypoints: [path.join(import.meta.dir, "entry.css")],
  outdir,
  plugins: [tailwind],
  target: "browser",
});

if (!result.success) {
  for (const log of result.logs) console.error(String(log));
  process.exit(1);
}
for (const output of result.outputs) {
  console.log(`${path.relative(frontendDir, output.path)}  ${(output.size / 1024).toFixed(1)} KB`);
}

// The converter lists tokens/*.css in the project README when they exist;
// without them it falls back to scraping every custom property out of the
// compiled bundle — which presents Tailwind internals (--tw-*, --animate-*,
// --default-*) as design tokens. Emit the real token set: the top-level
// :root and .dark blocks of styles/globals.css, verbatim.
// Normalized to LF: the checkout is CRLF on Windows (core.autocrlf), and the
// emitted file should not flip line endings between machines.
const globals = (await readFile(path.join(frontendDir, "styles", "globals.css"), "utf8")).replace(/\r\n/g, "\n");
const tokenBlocks = [":root", ".dark"].map((selector) => {
  const block = globals.match(new RegExp(`^${selector.replace(".", "\\.")} \\{\\n[\\s\\S]*?\\n\\}`, "m"));
  if (!block) {
    console.error(`tokens.css: no top-level \`${selector} {\` block found in styles/globals.css`);
    process.exit(1);
  }
  return block[0];
});
const tokensPath = path.join(outdir, "tokens.css");
await writeFile(
  tokensPath,
  `/* Bugler design tokens — generated by ds-css/build.ts from styles/globals.css
   (the :root and .dark token blocks, verbatim). The same declarations also ship
   inside _ds_bundle.css; this file exists so the design tokens are enumerable
   without scraping Tailwind internals out of the compiled stylesheet.
   Do not edit — edit styles/globals.css. */

${tokenBlocks.join("\n\n")}
`,
);
console.log(`${path.relative(frontendDir, tokensPath)}  (:root + .dark token blocks)`);
