<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="TngTech.ArchUnitNET.xUnit" Version="0.13.3" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Bugler.Host\Bugler.Host.csproj" />
    <ProjectReference Include="..\..\src\Bugler.Ingestion\Bugler.Ingestion.csproj" />
    <ProjectReference Include="..\..\src\Bugler.Exploration\Bugler.Exploration.csproj" />
    <ProjectReference Include="..\..\src\Bugler.Registry\Bugler.Registry.csproj" />
    <ProjectReference Include="..\..\src\Bugler.Access\Bugler.Access.csproj" />
    <ProjectReference Include="..\..\src\Bugler.Alerting\Bugler.Alerting.csproj" />
    <ProjectReference Include="..\..\src\Bugler.SharedKernel\Bugler.SharedKernel.csproj" />
    <ProjectReference Include="..\..\src\Bugler.Mail\Bugler.Mail.csproj" />
  </ItemGroup>

</Project>