<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Bugler.SharedKernel\Bugler.SharedKernel.csproj" />
    <ProjectReference Include="..\Bugler.Registry\Bugler.Registry.csproj" />
    <ProjectReference Include="..\Bugler.Access\Bugler.Access.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ModelContextProtocol.Core" Version="2.2.0" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <Using Include="Bugler.SharedKernel.ApplicationId" Alias="ApplicationId" />
  </ItemGroup>

</Project>
