// <auto-generated />
using System;
using Bugler.Alerting;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bugler.Alerting.Migrations
{
    [DbContext(typeof(AlertingDbContext))]
    [Migration("20260729221822_AddWatchFloor")]
    partial class AddWatchFloor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("alerting")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bugler.Alerting.Deliveries.Delivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<short>("Channel")
                        .HasColumnType("smallint")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("episode_id");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("LapsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lapsed_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_deliveries");

                    b.HasIndex("NextAttemptAt")
                        .HasDatabaseName("ix_deliveries_next_attempt_at")
                        .HasFilter("delivered_at IS NULL AND lapsed_at IS NULL");

                    b.HasIndex("EpisodeId", "Kind", "Channel", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_deliveries_episode_id_kind_channel_user_id");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("EpisodeId", "Kind", "Channel", "UserId"), false);

                    b.ToTable("deliveries", "alerting", t =>
                        {
                            t.HasCheckConstraint("ck_deliveries_mail_names_a_user", "(channel = 1) = (user_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Bugler.Alerting.DetectEpisodes.PollCursor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<long>("LastLogId")
                        .HasColumnType("bigint")
                        .HasColumnName("last_log_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("WatchFloor")
                        .HasColumnType("bigint")
                        .HasColumnName("watch_floor");

                    b.HasKey("Id")
                        .HasName("pk_poll_cursor");

                    b.ToTable("poll_cursor", "alerting");
                });

            modelBuilder.Entity("Bugler.Alerting.DetectEpisodes.SeenLogId", b =>
                {
                    b.Property<long>("LogId")
                        .HasColumnType("bigint")
                        .HasColumnName("log_id");

                    b.HasKey("LogId")
                        .HasName("pk_seen_log_ids");

                    b.ToTable("seen_log_ids", "alerting");
                });

            modelBuilder.Entity("Bugler.Alerting.Episodes.Episode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<short?>("CloseReason")
                        .HasColumnType("smallint")
                        .HasColumnName("close_reason");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer")
                        .HasColumnName("error_count");

                    b.Property<string>("FirstLogBody")
                        .HasColumnType("text")
                        .HasColumnName("first_log_body");

                    b.Property<long>("FirstLogId")
                        .HasColumnType("bigint")
                        .HasColumnName("first_log_id");

                    b.Property<short>("FirstLogSeverity")
                        .HasColumnType("smallint")
                        .HasColumnName("first_log_severity");

                    b.Property<DateTimeOffset>("FirstLogTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_log_timestamp");

                    b.Property<DateTimeOffset>("LastMatchAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_match_at");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<int>("WarnCount")
                        .HasColumnType("integer")
                        .HasColumnName("warn_count");

                    b.HasKey("Id")
                        .HasName("pk_episodes");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_episodes_application_id");

                    b.HasIndex("ServiceId")
                        .IsUnique()
                        .HasDatabaseName("ix_episodes_one_open_per_service")
                        .HasFilter("closed_at IS NULL");

                    b.HasIndex("OpenedAt", "Id")
                        .HasDatabaseName("ix_episodes_opened_at_id");

                    b.ToTable("episodes", "alerting");
                });

            modelBuilder.Entity("Bugler.Alerting.Settings.ApplicationAlertingSettings", b =>
                {
                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<string>("ChatWebhookUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("chat_webhook_url");

                    b.Property<int?>("QuietWindowMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("quiet_window_minutes");

                    b.Property<short?>("Sensitivity")
                        .HasColumnType("smallint")
                        .HasColumnName("sensitivity");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ApplicationId")
                        .HasName("pk_application_settings");

                    b.ToTable("application_settings", "alerting", t =>
                        {
                            t.HasCheckConstraint("ck_application_settings_quiet_window", "quiet_window_minutes >= 1");
                        });
                });

            modelBuilder.Entity("Bugler.Alerting.Settings.ServiceAlertingSettings", b =>
                {
                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<int?>("QuietWindowMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("quiet_window_minutes");

                    b.Property<short?>("Sensitivity")
                        .HasColumnType("smallint")
                        .HasColumnName("sensitivity");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ServiceId")
                        .HasName("pk_service_settings");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_service_settings_application_id");

                    b.ToTable("service_settings", "alerting", t =>
                        {
                            t.HasCheckConstraint("ck_service_settings_quiet_window", "quiet_window_minutes >= 1");
                        });
                });

            modelBuilder.Entity("Bugler.Alerting.Subscriptions.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_subscriptions");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_subscriptions_application_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_subscriptions_service_id");

                    b.HasIndex("UserId", "ApplicationId")
                        .IsUnique()
                        .HasDatabaseName("ix_subscriptions_user_id_application_id")
                        .HasFilter("application_id IS NOT NULL");

                    b.HasIndex("UserId", "ServiceId")
                        .IsUnique()
                        .HasDatabaseName("ix_subscriptions_user_id_service_id")
                        .HasFilter("service_id IS NOT NULL");

                    b.ToTable("subscriptions", "alerting", t =>
                        {
                            t.HasCheckConstraint("ck_subscriptions_one_target", "(application_id IS NULL) <> (service_id IS NULL)");
                        });
                });

            modelBuilder.Entity("Bugler.Alerting.Deliveries.Delivery", b =>
                {
                    b.HasOne("Bugler.Alerting.Episodes.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deliveries_episodes_episode_id");
                });
#pragma warning restore 612, 618
        }
    }
}
