// <auto-generated />
using System;
using Bugler.Alerting;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bugler.Alerting.Migrations
{
    [DbContext(typeof(AlertingDbContext))]
    partial class AlertingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("alerting")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bugler.Alerting.Deliveries.Delivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<short>("Channel")
                        .HasColumnType("smallint")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("episode_id");

                    b.Property<int?>("FoldedEpisodeCount")
                        .HasColumnType("integer")
                        .HasColumnName("folded_episode_count");

                    b.Property<Guid?>("JoiningServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("joining_service_id");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("LapsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lapsed_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_deliveries");

                    b.HasIndex("NextAttemptAt")
                        .HasDatabaseName("ix_deliveries_next_attempt_at")
                        .HasFilter("delivered_at IS NULL AND lapsed_at IS NULL");

                    b.HasIndex("EpisodeId", "Kind", "Channel", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_deliveries_episode_id_kind_channel_user_id")
                        .HasFilter("kind IN (1, 2, 4, 5)");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("EpisodeId", "Kind", "Channel", "UserId"), false);

                    b.ToTable("deliveries", "alerting", t =>
                        {
                            t.HasCheckConstraint("ck_deliveries_mail_names_a_user", "(channel = 1) = (user_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Bugler.Alerting.DetectEpisodes.PollCursor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<long>("LastLogId")
                        .HasColumnType("bigint")
                        .HasColumnName("last_log_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("WatchFloor")
                        .HasColumnType("bigint")
                        .HasColumnName("watch_floor");

                    b.HasKey("Id")
                        .HasName("pk_poll_cursor");

                    b.ToTable("poll_cursor", "alerting");
                });

            modelBuilder.Entity("Bugler.Alerting.DetectEpisodes.SeenLogId", b =>
                {
                    b.Property<long>("LogId")
                        .HasColumnType("bigint")
                        .HasColumnName("log_id");

                    b.HasKey("LogId")
                        .HasName("pk_seen_log_ids");

                    b.ToTable("seen_log_ids", "alerting");
                });

            modelBuilder.Entity("Bugler.Alerting.Episodes.Episode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<Guid?>("AcknowledgedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("acknowledged_by_user_id");

                    b.Property<bool>("AlertFoldedIntoStorm")
                        .HasColumnType("boolean")
                        .HasColumnName("alert_folded_into_storm");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<DateTimeOffset?>("ClaimLeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claim_lease_until");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<Guid?>("ClaimedByDelegationId")
                        .HasColumnType("uuid")
                        .HasColumnName("claimed_by_delegation_id");

                    b.Property<Guid?>("ClaimedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("claimed_by_user_id");

                    b.Property<short?>("CloseReason")
                        .HasColumnType("smallint")
                        .HasColumnName("close_reason");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer")
                        .HasColumnName("error_count");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("fingerprint");

                    b.Property<short>("FingerprintRung")
                        .HasColumnType("smallint")
                        .HasColumnName("fingerprint_rung");

                    b.Property<DateTimeOffset>("FirstMatchAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_match_at");

                    b.Property<string>("FirstMatchDetail")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("first_match_detail");

                    b.Property<long?>("FirstMatchLogId")
                        .HasColumnType("bigint")
                        .HasColumnName("first_match_log_id");

                    b.Property<short?>("FirstMatchSeverity")
                        .HasColumnType("smallint")
                        .HasColumnName("first_match_severity");

                    b.Property<DateTimeOffset>("LastMatchAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_match_at");

                    b.Property<Guid?>("NoteByDelegationId")
                        .HasColumnType("uuid")
                        .HasColumnName("note_by_delegation_id");

                    b.Property<string>("NoteLink")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note_link");

                    b.Property<string>("NoteText")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("note_text");

                    b.Property<DateTimeOffset?>("NotedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("noted_at");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<Guid?>("OpenedByServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("opened_by_service_id");

                    b.Property<Guid?>("ProposalByDelegationId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposal_by_delegation_id");

                    b.Property<string>("ProposalLink")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("proposal_link");

                    b.Property<int?>("ProposalMatchesWhenLaid")
                        .HasColumnType("integer")
                        .HasColumnName("proposal_matches_when_laid");

                    b.Property<DateTimeOffset?>("ProposedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proposed_at");

                    b.Property<int>("RecipeVersion")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_version");

                    b.Property<string>("ResignationReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("resignation_reason");

                    b.Property<DateTimeOffset?>("ResignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resigned_at");

                    b.Property<Guid?>("ResignedByDelegationId")
                        .HasColumnType("uuid")
                        .HasColumnName("resigned_by_delegation_id");

                    b.Property<string>("ScopeKey")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("character varying(700)")
                        .HasColumnName("scope_key");

                    b.Property<DateTimeOffset?>("SolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("solved_at");

                    b.Property<Guid?>("SolvedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("solved_by_user_id");

                    b.Property<bool>("StackTruncated")
                        .HasColumnType("boolean")
                        .HasColumnName("stack_truncated");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<int>("WarnCount")
                        .HasColumnType("integer")
                        .HasColumnName("warn_count");

                    b.Property<short>("Watch")
                        .HasColumnType("smallint")
                        .HasColumnName("watch");

                    b.HasKey("Id")
                        .HasName("pk_episodes");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_episodes_application_id");

                    b.HasIndex("ClaimLeaseUntil")
                        .HasDatabaseName("ix_episodes_claim_lease_until")
                        .HasFilter("claimed_by_delegation_id IS NOT NULL");

                    b.HasIndex("OpenedAt", "Id")
                        .HasDatabaseName("ix_episodes_opened_at_id");

                    b.HasIndex(new[] { "ScopeKey", "Fingerprint" }, "kind_history")
                        .HasDatabaseName("ix_episodes_kind_history");

                    b.HasIndex(new[] { "ScopeKey", "Watch", "Fingerprint" }, "one_open_per_kind")
                        .IsUnique()
                        .HasDatabaseName("ix_episodes_one_open_per_kind")
                        .HasFilter("closed_at IS NULL");

                    b.ToTable("episodes", "alerting");
                });

            modelBuilder.Entity("Bugler.Alerting.Episodes.JournalEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<Guid?>("DelegationId")
                        .HasColumnType("uuid")
                        .HasColumnName("delegation_id");

                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("episode_id");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_journal_entries");

                    b.HasIndex("EpisodeId")
                        .HasDatabaseName("ix_journal_entries_episode_id");

                    b.ToTable("journal_entries", "alerting");
                });

            modelBuilder.Entity("Bugler.Alerting.Episodes.Participation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("episode_id");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer")
                        .HasColumnName("error_count");

                    b.Property<DateTimeOffset>("FirstAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_at");

                    b.Property<DateTimeOffset>("LastAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_at");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<string>("Version")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("version");

                    b.Property<int>("WarnCount")
                        .HasColumnType("integer")
                        .HasColumnName("warn_count");

                    b.HasKey("Id")
                        .HasName("pk_participations");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_participations_service_id");

                    b.HasIndex("EpisodeId", "ServiceId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_participations_episode_id_service_id_version");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("EpisodeId", "ServiceId", "Version"), false);

                    b.ToTable("participations", "alerting");
                });

            modelBuilder.Entity("Bugler.Alerting.Readings.Reading", b =>
                {
                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("episode_id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Czech")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("czech");

                    b.Property<string>("English")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("english");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<DateTimeOffset?>("WrittenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("written_at");

                    b.HasKey("EpisodeId")
                        .HasName("pk_readings");

                    b.HasIndex("NextAttemptAt")
                        .HasDatabaseName("ix_readings_next_attempt_at")
                        .HasFilter("written_at IS NULL AND failed_at IS NULL");

                    b.ToTable("readings", "alerting");
                });

            modelBuilder.Entity("Bugler.Alerting.Settings.ApplicationAlertingSettings", b =>
                {
                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<string>("ChatWebhookUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("chat_webhook_url");

                    b.Property<int?>("ClaimLeaseHours")
                        .HasColumnType("integer")
                        .HasColumnName("claim_lease_hours");

                    b.Property<string>("FingerprintAttributeKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("fingerprint_attribute_key");

                    b.Property<short?>("FingerprintRule")
                        .HasColumnType("smallint")
                        .HasColumnName("fingerprint_rule");

                    b.Property<int?>("QuietWindowMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("quiet_window_minutes");

                    b.Property<bool?>("ScopeByEnvironment")
                        .HasColumnType("boolean")
                        .HasColumnName("scope_by_environment");

                    b.Property<bool?>("ScopeByNamespace")
                        .HasColumnType("boolean")
                        .HasColumnName("scope_by_namespace");

                    b.Property<bool?>("ScopeByServiceName")
                        .HasColumnType("boolean")
                        .HasColumnName("scope_by_service_name");

                    b.Property<short?>("Sensitivity")
                        .HasColumnType("smallint")
                        .HasColumnName("sensitivity");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ApplicationId")
                        .HasName("pk_application_settings");

                    b.ToTable("application_settings", "alerting", t =>
                        {
                            t.HasCheckConstraint("ck_application_settings_claim_lease", "claim_lease_hours >= 1");

                            t.HasCheckConstraint("ck_application_settings_quiet_window", "quiet_window_minutes >= 1");
                        });
                });

            modelBuilder.Entity("Bugler.Alerting.Settings.FingerprintQuietWindow", b =>
                {
                    b.Property<string>("ScopeKey")
                        .HasMaxLength(700)
                        .HasColumnType("character varying(700)")
                        .HasColumnName("scope_key");

                    b.Property<string>("Fingerprint")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("fingerprint");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<int>("QuietWindowMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("quiet_window_minutes");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ScopeKey", "Fingerprint")
                        .HasName("pk_fingerprint_quiet_windows");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_fingerprint_quiet_windows_application_id");

                    b.ToTable("fingerprint_quiet_windows", "alerting", t =>
                        {
                            t.HasCheckConstraint("ck_fingerprint_quiet_windows_bounds", "quiet_window_minutes BETWEEN 1 AND 10080");
                        });
                });

            modelBuilder.Entity("Bugler.Alerting.Settings.ServiceAlertingSettings", b =>
                {
                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<string>("HealthCheckUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("health_check_url");

                    b.Property<int?>("QuietWindowMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("quiet_window_minutes");

                    b.Property<short?>("Sensitivity")
                        .HasColumnType("smallint")
                        .HasColumnName("sensitivity");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ServiceId")
                        .HasName("pk_service_settings");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_service_settings_application_id");

                    b.ToTable("service_settings", "alerting", t =>
                        {
                            t.HasCheckConstraint("ck_service_settings_quiet_window", "quiet_window_minutes >= 1");
                        });
                });

            modelBuilder.Entity("Bugler.Alerting.Subscriptions.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_subscriptions");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_subscriptions_application_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_subscriptions_service_id");

                    b.HasIndex("UserId", "ApplicationId")
                        .IsUnique()
                        .HasDatabaseName("ix_subscriptions_user_id_application_id")
                        .HasFilter("application_id IS NOT NULL");

                    b.HasIndex("UserId", "ServiceId")
                        .IsUnique()
                        .HasDatabaseName("ix_subscriptions_user_id_service_id")
                        .HasFilter("service_id IS NOT NULL");

                    b.ToTable("subscriptions", "alerting", t =>
                        {
                            t.HasCheckConstraint("ck_subscriptions_one_target", "(application_id IS NULL) <> (service_id IS NULL)");
                        });
                });

            modelBuilder.Entity("Bugler.Alerting.Deliveries.Delivery", b =>
                {
                    b.HasOne("Bugler.Alerting.Episodes.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deliveries_episodes_episode_id");
                });

            modelBuilder.Entity("Bugler.Alerting.Episodes.JournalEntry", b =>
                {
                    b.HasOne("Bugler.Alerting.Episodes.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_journal_entries_episodes_episode_id");
                });

            modelBuilder.Entity("Bugler.Alerting.Episodes.Participation", b =>
                {
                    b.HasOne("Bugler.Alerting.Episodes.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_participations_episodes_episode_id");
                });

            modelBuilder.Entity("Bugler.Alerting.Readings.Reading", b =>
                {
                    b.HasOne("Bugler.Alerting.Episodes.Episode", null)
                        .WithOne()
                        .HasForeignKey("Bugler.Alerting.Readings.Reading", "EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_readings_episodes_episode_id");
                });
#pragma warning restore 612, 618
        }
    }
}
